export default {
  GB: [
    { code: "HSBC", name: "HSBC UK" },
    { code: "BARC", name: "Barclays Bank" },
    { code: "LLOYDS", name: "Lloyds Bank" },
    { code: "NATWEST", name: "NatWest Bank" },
    { code: "SANTANDER", name: "Santander UK" },
    { code: "TSB", name: "TSB Bank" },
    { code: "METRO", name: "Metro Bank" },
    { code: "STARLING", name: "Starling Bank" },
    { code: "MONZO", name: "Monzo Bank" },
    { code: "REVOLUT", name: "Revolut Bank UK" },
  ],
  ID: [
    { code: "BBCA", name: "Bank Central Asia" },
    { code: "BBRI", name: "Bank Rakyat Indonesia" },
    { code: "BMRI", name: "Bank Mandiri" },
    { code: "BBNI", name: "Bank Negara Indonesia" },
    { code: "CIMBN", name: "CIMB Niaga" },
    { code: "DANAMON", name: "Bank Danamon" },
    { code: "PERMATA", name: "Bank Permata" },
    { code: "BTN", name: "Bank Tabungan Negara" },
    { code: "PANIN", name: "Panin Bank" },
    { code: "MEGA", name: "Bank Mega" },
  ],
  JP: [
    { code: "MUFG", name: "Mitsubishi UFJ Financial Group Bank" },
    { code: "SMBC", name: "Sumitomo Mitsui Banking Corporation" },
    { code: "MIZUHO", name: "Mizuho Bank" },
    { code: "JPBANK", name: "Japan Post Bank" },
    { code: "RESONA", name: "Resona Bank" },
    { code: "SHINSEI", name: "Shinsei Bank" },
    { code: "AOZORA", name: "Aozora Bank" },
    { code: "NORIN", name: "Norinchukin Bank" },
    { code: "SEVEN", name: "Seven Bank" },
    { code: "RAKUTEN", name: "Rakuten Bank" },
  ],
  KR: [
    { code: "KB", name: "KB Kookmin Bank" },
    { code: "SHINHAN", name: "Shinhan Bank" },
    { code: "WOORI", name: "Woori Bank" },
    { code: "HANA", name: "Hana Bank" },
    { code: "IBK", name: "Industrial Bank of Korea" },
    { code: "SC", name: "Standard Chartered Korea" },
    { code: "CITI", name: "Citibank Korea" },
    { code: "KDB", name: "Korea Development Bank" },
    { code: "BNK", name: "BNK Busan Bank" },
    { code: "DGB", name: "DGB Daegu Bank" },
  ],
  LA: [
    { code: "BCEL", name: "Banque Pour Le Commerce Exterieur Lao Public" },
    { code: "LDB", name: "Lao Development Bank" },
    { code: "APB", name: "Agricultural Promotion Bank" },
    { code: "PHB", name: "Phongsavanh Bank" },
    { code: "JDB", name: "Joint Development Bank" },
    { code: "LVB", name: "Lao-Viet Bank" },
    { code: "BFL", name: "Banque Franco-Lao" },
    { code: "LCNB", name: "Lao China Bank" },
    { code: "MJBL", name: "Maruhan Japan Bank Lao" },
    { code: "STB", name: "ST Bank Laos" },
  ],
  MY: [
    { code: "MBB", name: "Maybank" },
    { code: "CIMB", name: "CIMB Bank" },
    { code: "PBB", name: "Public Bank" },
    { code: "RHB", name: "RHB Bank" },
    { code: "HLB", name: "Hong Leong Bank" },
    { code: "AMB", name: "AmBank" },
    { code: "AFFIN", name: "Affin Bank" },
    { code: "BSN", name: "Bank Simpanan Nasional" },
    { code: "AGRO", name: "Agrobank" },
    { code: "UOBM", name: "UOB Malaysia" },
  ],
  PH: [
    { code: "BDO", name: "BDO Unibank" },
    { code: "BPI", name: "Bank of the Philippine Islands" },
    { code: "MBT", name: "Metropolitan Bank & Trust" },
    { code: "LANDBANK", name: "Land Bank of the Philippines" },
    { code: "PNB", name: "Philippine National Bank" },
    { code: "RCBC", name: "Rizal Commercial Banking Corporation" },
    { code: "SECURITY", name: "Security Bank" },
    { code: "EASTWEST", name: "EastWest Bank" },
    { code: "CHINABANK", name: "China Banking Corporation" },
    { code: "UNION", name: "UnionBank" },
  ],
  SG: [
    { code: "DBS", name: "DBS Bank" },
    { code: "OCBC", name: "OCBC Bank" },
    { code: "UOB", name: "United Overseas Bank" },
    { code: "CITI", name: "Citibank Singapore" },
    { code: "HSBC", name: "HSBC Singapore" },
    { code: "SCB", name: "Standard Chartered Singapore" },
    { code: "MAYBANK", name: "Maybank Singapore" },
    { code: "RHB", name: "RHB Bank Singapore" },
    { code: "ICBC", name: "ICBC Singapore" },
    { code: "BOC", name: "Bank of China Singapore" },
  ],
  TH: [
    { code: "BBL", name: "Bangkok Bank" },
    { code: "KBANK", name: "Kasikornbank" },
    { code: "SCB", name: "Siam Commercial Bank" },
    { code: "KTB", name: "Krung Thai Bank" },
    { code: "BAY", name: "Bank of Ayudhya (Krungsri)" },
    { code: "TTB", name: "TMBThanachart Bank" },
    { code: "GSB", name: "Government Savings Bank" },
    { code: "BAAC", name: "Bank for Agriculture and Agricultural Cooperatives" },
    { code: "UOBT", name: "UOB Thailand" },
    { code: "CIMBT", name: "CIMB Thai Bank" },
  ],
  US: [
    { code: "JPM", name: "JPMorgan Chase Bank" },
    { code: "BOA", name: "Bank of America" },
    { code: "WFC", name: "Wells Fargo Bank" },
    { code: "CITI", name: "Citibank" },
    { code: "USB", name: "U.S. Bank" },
    { code: "PNC", name: "PNC Bank" },
    { code: "TRUIST", name: "Truist Bank" },
    { code: "CAP1", name: "Capital One Bank" },
    { code: "TD", name: "TD Bank USA" },
    { code: "BMO", name: "BMO Harris Bank" },
  ],
  VN: [
    { code: "VCB", name: "Vietcombank" },
    { code: "BIDV", name: "Bank for Investment and Development of Vietnam" },
    { code: "CTG", name: "VietinBank" },
    { code: "ACB", name: "Asia Commercial Bank" },
    { code: "TCB", name: "Techcombank" },
    { code: "MBB", name: "Military Commercial Joint Stock Bank" },
    { code: "VPB", name: "VPBank" },
    { code: "STB", name: "Sacombank" },
    { code: "HDB", name: "HDBank" },
    { code: "VIB", name: "Vietnam International Bank" },
  ],
}
